sudo -i (to become root user)
apt update -y (update the pre-installed packages)
apt install php php-mysqlnd -y ( installation of php and mysql connecter)
apt install apache2 -y (installation of apache2)
apt install mysql-server -y (installation of mysql)
wget https://wordpress.org/latest.tar.gz (to get resources from link)
tar -xvzf latest.tar.gz (to unzip the tar file)
mv  (move a file and change name)
cd  (change directory)
rm (to remove or delete)
